services:
  - type: web
    name: color-studio-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
